In [35]:
# getting our data...
import h5py
##
# We have 1284 examples
# x feature set is 20 x 325
# y ranges from -3 to 3 (float)
##
x_train_dataset = h5py.File('../cmu-mosi/seq_length_20/X_train.h5', 'r')['data']
y_train_dataset = h5py.File('../cmu-mosi/seq_length_20/y_train.h5', 'r')['data']

# x_train_dataset
print(x_train_dataset)

<HDF5 dataset "data": shape (1284, 20, 325), type "<f8">


In [34]:
# dataloader
from torch.utils import data
data_loader = data.DataLoader(y_train_dataset)

num_epochs = 3
for i in range(num_epochs):
   for x in data_loader:
      print(x)
      pass


tensor([-0.5000], dtype=torch.float64)
tensor([-1.2000], dtype=torch.float64)
tensor([1.8000], dtype=torch.float64)
tensor([2.2000], dtype=torch.float64)
tensor([2.4000], dtype=torch.float64)
tensor([-1.], dtype=torch.float64)
tensor([-0.8000], dtype=torch.float64)
tensor([0.], dtype=torch.float64)
tensor([-1.7500], dtype=torch.float64)
tensor([0.8000], dtype=torch.float64)
tensor([0.], dtype=torch.float64)
tensor([0.2000], dtype=torch.float64)
tensor([0.], dtype=torch.float64)
tensor([2.6000], dtype=torch.float64)
tensor([2.2000], dtype=torch.float64)
tensor([0.6000], dtype=torch.float64)
tensor([2.], dtype=torch.float64)
tensor([1.8000], dtype=torch.float64)
tensor([2.6000], dtype=torch.float64)
tensor([-0.4000], dtype=torch.float64)
tensor([-0.2000], dtype=torch.float64)
tensor([-2.8000], dtype=torch.float64)
tensor([0.8000], dtype=torch.float64)
tensor([-1.4000], dtype=torch.float64)
tensor([1.8000], dtype=torch.float64)
tensor([-1.4000], dtype=torch.float64)
tensor([-1.], dtype=to

tensor([2.], dtype=torch.float64)
tensor([2.2000], dtype=torch.float64)
tensor([1.4000], dtype=torch.float64)
tensor([2.], dtype=torch.float64)
tensor([1.8000], dtype=torch.float64)
tensor([0.2500], dtype=torch.float64)
tensor([-0.4000], dtype=torch.float64)
tensor([0.], dtype=torch.float64)
tensor([0.], dtype=torch.float64)
tensor([0.6000], dtype=torch.float64)
tensor([-1.4000], dtype=torch.float64)
tensor([0.], dtype=torch.float64)
tensor([2.4000], dtype=torch.float64)
tensor([2.6000], dtype=torch.float64)
tensor([1.2000], dtype=torch.float64)
tensor([1.], dtype=torch.float64)
tensor([1.6000], dtype=torch.float64)
tensor([1.], dtype=torch.float64)
tensor([1.6000], dtype=torch.float64)
tensor([2.8000], dtype=torch.float64)
tensor([0.8000], dtype=torch.float64)
tensor([0.5000], dtype=torch.float64)
tensor([1.6000], dtype=torch.float64)
tensor([2.2000], dtype=torch.float64)
tensor([-0.2000], dtype=torch.float64)
tensor([-1.2000], dtype=torch.float64)
tensor([-1.4000], dtype=torch.float6

tensor([0.8000], dtype=torch.float64)
tensor([1.6000], dtype=torch.float64)
tensor([-0.6000], dtype=torch.float64)
tensor([2.], dtype=torch.float64)
tensor([-1.2000], dtype=torch.float64)
tensor([1.4000], dtype=torch.float64)
tensor([-0.6000], dtype=torch.float64)
tensor([-1.2000], dtype=torch.float64)
tensor([-1.6000], dtype=torch.float64)
tensor([0.], dtype=torch.float64)
tensor([-0.4000], dtype=torch.float64)
tensor([-0.2000], dtype=torch.float64)
tensor([-1.2000], dtype=torch.float64)
tensor([-1.6000], dtype=torch.float64)
tensor([1.], dtype=torch.float64)
tensor([-0.8000], dtype=torch.float64)
tensor([-0.8000], dtype=torch.float64)
tensor([-0.8000], dtype=torch.float64)
tensor([1.6000], dtype=torch.float64)
tensor([1.4000], dtype=torch.float64)
tensor([1.8000], dtype=torch.float64)
tensor([0.5000], dtype=torch.float64)
tensor([1.8000], dtype=torch.float64)
tensor([2.4000], dtype=torch.float64)
tensor([2.6000], dtype=torch.float64)
tensor([1.8000], dtype=torch.float64)
tensor([2.],

tensor([-2.], dtype=torch.float64)
tensor([-2.4000], dtype=torch.float64)
tensor([-1.2000], dtype=torch.float64)
tensor([-0.5000], dtype=torch.float64)
tensor([-2.], dtype=torch.float64)
tensor([-0.2000], dtype=torch.float64)
tensor([1.2000], dtype=torch.float64)
tensor([-0.4000], dtype=torch.float64)
tensor([-0.4000], dtype=torch.float64)
tensor([-2.8000], dtype=torch.float64)
tensor([-0.2000], dtype=torch.float64)
tensor([-0.8000], dtype=torch.float64)
tensor([1.8000], dtype=torch.float64)
tensor([1.8000], dtype=torch.float64)
tensor([-3.], dtype=torch.float64)
tensor([-1.], dtype=torch.float64)
tensor([-2.], dtype=torch.float64)
tensor([-1.4000], dtype=torch.float64)
tensor([-1.8000], dtype=torch.float64)
tensor([-2.], dtype=torch.float64)
tensor([-1.2000], dtype=torch.float64)
tensor([-1.], dtype=torch.float64)
tensor([-2.2000], dtype=torch.float64)
tensor([-2.2000], dtype=torch.float64)
tensor([-2.4000], dtype=torch.float64)
tensor([-1.4000], dtype=torch.float64)
tensor([1.6000], 

tensor([0.5000], dtype=torch.float64)
tensor([2.4000], dtype=torch.float64)
tensor([0.6000], dtype=torch.float64)
tensor([0.6000], dtype=torch.float64)
tensor([-1.], dtype=torch.float64)
tensor([-0.6000], dtype=torch.float64)
tensor([-0.8000], dtype=torch.float64)
tensor([0.], dtype=torch.float64)
tensor([0.4000], dtype=torch.float64)
tensor([0.2000], dtype=torch.float64)
tensor([-0.5000], dtype=torch.float64)
tensor([-0.4000], dtype=torch.float64)
tensor([1.6000], dtype=torch.float64)
tensor([-1.8000], dtype=torch.float64)
tensor([-0.8000], dtype=torch.float64)
tensor([-0.8000], dtype=torch.float64)
tensor([1.], dtype=torch.float64)
tensor([1.6000], dtype=torch.float64)
tensor([-1.8000], dtype=torch.float64)
tensor([0.], dtype=torch.float64)
tensor([-1.2000], dtype=torch.float64)
tensor([2.6000], dtype=torch.float64)
tensor([2.2000], dtype=torch.float64)
tensor([-0.4000], dtype=torch.float64)
tensor([2.], dtype=torch.float64)
tensor([0.], dtype=torch.float64)
tensor([2.6000], dtype=to

tensor([0.8000], dtype=torch.float64)
tensor([1.8000], dtype=torch.float64)
tensor([-1.4000], dtype=torch.float64)
tensor([2.4000], dtype=torch.float64)
tensor([2.6000], dtype=torch.float64)
tensor([-1.2000], dtype=torch.float64)
tensor([2.2000], dtype=torch.float64)
tensor([-1.8000], dtype=torch.float64)
tensor([0.4000], dtype=torch.float64)
tensor([1.2000], dtype=torch.float64)
tensor([-1.6000], dtype=torch.float64)
tensor([2.6000], dtype=torch.float64)
tensor([-2.4000], dtype=torch.float64)
tensor([-1.], dtype=torch.float64)
tensor([0.8000], dtype=torch.float64)
tensor([-2.], dtype=torch.float64)
tensor([-1.4000], dtype=torch.float64)
tensor([2.], dtype=torch.float64)
tensor([-1.6000], dtype=torch.float64)
tensor([-2.], dtype=torch.float64)
tensor([-1.8000], dtype=torch.float64)
tensor([2.6000], dtype=torch.float64)
tensor([3.], dtype=torch.float64)
tensor([-1.6000], dtype=torch.float64)
tensor([-2.], dtype=torch.float64)
tensor([-1.6000], dtype=torch.float64)
tensor([1.4000], dtype